spring:
  profiles:
    active: local

---
#spring profiles : LOCAL
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/basquiat?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000 # 10 sec.
      maximum-pool-size: 10
      pool-name: basquiat-pool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: io.basquiat.common.handler.CustomMySpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    allow-bean-definition-overriding: true
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: localhost
    password:
    port: 6379

rabbitmq:
  host: localhost
  port: 5672
  virtualHost: /
  userId: basquiat
  password: basquiat
  exchange: basquiat
  cache: cache

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  config: classpath:logback.xml
  level:
    root: info
    org:
      hibernate:
        type: trace

entity:
  catalog: basquiat